### ISSUE TITLE
There are no @api.one and @api.multi in Odoo13.

### ISSUE THREAD

**Issue by pengz1234** [itpp-labs/odoo-development#221]
I am tring to create a one2one relation.But,I open api.py and find there are no one and multi functions in it,maybe Odoo13 has removed them.
How can I make a one2one relation?

**Comment by yelizariev** [comment]
Hi!

@api.multi is used by default. So, you need to rewrite the methods from api.one to api.multi

If you figure it out, please send  a pull request with page update: https://github.com/itpp-labs/odoo-development/blob/master/docs/dev/py/one2one.rst

**Comment by pengz1234** [comment]
Finally, I use Many2one to replace one2one.
Thanks a lot.
