### ISSUE TITLE
Activate debug mode in 13.0

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/odoo-development#224]
It's doesn't work in 13.0:
https://github.com/itpp-labs/odoo-development/blob/f232266801bdedae15125d9b70c373e4c0d9c288/docs/odoo/usage/debug-mode.rst#L7

Need to use `?debug=True` instead

**Comment by yelizariev** [comment]
?debug=1 works fine for me

![image](https://user-images.githubusercontent.com/186131/90235493-d3235900-de3a-11ea-9401-fed81f4bbc34.png)

https://3856488-13-0.runbot47.odoo.com/web?debug=1#action=74&cids=1&menu_id=4&model=res.users&view_type=list

**Comment by trojikman** [comment]
> ?debug=1 works fine for me
> 
> ![image](https://user-images.githubusercontent.com/186131/90235493-d3235900-de3a-11ea-9401-fed81f4bbc34.png)
> 
> https://3856488-13-0.runbot47.odoo.com/web?debug=1#action=74&cids=1&menu_id=4&model=res.users&view_type=list

My bad
